name: Deploy Jekyll Site to Pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Jekyll Site
        uses: actions/jekyll-build-pages@v1.0.13  # Use the latest version

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3  # Use the latest version
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
  jobs:
    deploy:
      runs-on: ubuntu-latest
      permissions:
        id-token: write  # Required for actions/deploy-pages
      steps:
        - name: Deploy pages
          uses: actions/deploy-pages@v4
        uses: actions/deploy-pages@v4  # Optional, if deploying
